/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.AdminRole;
import backend.LibrarianUser;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author LENOVO
 */
public class AdminRoleWindow extends javax.swing.JFrame implements Node {

    private Node parent;
    private AddLibrarianWindow addLibrarian;
    private ViewLibrariansWindow viewLibrarians;
    private RemoveLibrarianWindow removeLibrarian;
    private AdminRole adminRole;
    /**
     * Creates new form AdminRoleWindow
     * @throws java.io.FileNotFoundException
     */
    public AdminRoleWindow() throws FileNotFoundException {
        initComponents();
        this.setTitle("Admin Role");
        addLibrarian = null;
        viewLibrarians = null;
        removeLibrarian = null;
        adminRole = new AdminRole();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddLibrarianButton = new javax.swing.JButton();
        ViewLibrariansButton = new javax.swing.JButton();
        RemoveLibrarianButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        AddLibrarianButton.setBackground(new java.awt.Color(0, 0, 0));
        AddLibrarianButton.setForeground(new java.awt.Color(255, 255, 255));
        AddLibrarianButton.setText("Add Librarian");
        AddLibrarianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLibrarianButtonActionPerformed(evt);
            }
        });

        ViewLibrariansButton.setBackground(new java.awt.Color(0, 0, 0));
        ViewLibrariansButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewLibrariansButton.setText("View Librarians");
        ViewLibrariansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewLibrariansButtonActionPerformed(evt);
            }
        });

        RemoveLibrarianButton.setBackground(new java.awt.Color(0, 0, 0));
        RemoveLibrarianButton.setForeground(new java.awt.Color(255, 255, 255));
        RemoveLibrarianButton.setText("Remove Librarian");
        RemoveLibrarianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveLibrarianButtonActionPerformed(evt);
            }
        });

        LogoutButton.setBackground(new java.awt.Color(0, 0, 0));
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RemoveLibrarianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddLibrarianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewLibrariansButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(AddLibrarianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewLibrariansButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RemoveLibrarianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddLibrarianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLibrarianButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if(addLibrarian == null){
            try {
                addLibrarian = new AddLibrarianWindow(adminRole);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(AdminRoleWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            addLibrarian.setParentNode(this);
            addLibrarian.setVisible(true);
        }
    }//GEN-LAST:event_AddLibrarianButtonActionPerformed

    private void RemoveLibrarianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveLibrarianButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if(removeLibrarian == null){
            try {
                removeLibrarian = new RemoveLibrarianWindow(adminRole);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(AdminRoleWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            removeLibrarian.setParentNode(this);
            removeLibrarian.setVisible(true);
        }
    }//GEN-LAST:event_RemoveLibrarianButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        try {
            adminRole.logout();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminRoleWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void ViewLibrariansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewLibrariansButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if(viewLibrarians == null){
            viewLibrarians = new ViewLibrariansWindow(new String[] {"Librarian Id","Name","Email","Address","Phone Number"});
            viewLibrarians.setParentNode(this);
        }
        LibrarianUser [] lu = adminRole.getListOfLibrarians();
        String [][] tableData = new String[lu.length][5];
        for(int i=0; i<lu.length; i++){
            tableData[i] = lu[i].lineRepresentation().split(",");
        }
        viewLibrarians.setData(tableData);
         viewLibrarians.setVisible(true);
    }//GEN-LAST:event_ViewLibrariansButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdminRoleWindow().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(AdminRoleWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddLibrarianButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton RemoveLibrarianButton;
    private javax.swing.JButton ViewLibrariansButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public Node getParentNode() {
        return parent;
    }

    @Override
    public void setParentNode(Node node) {
        this.parent = node;
    }
}
