/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Book;
import backend.LibrarianRole;
import backend.LibrarianUser;
import backend.StudentBook;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author LENOVO
 */
public class LibrarianRoleWindow extends javax.swing.JFrame implements Node{

    private Node parent;
    private AddBookWindow addBook;
    private BorrowBookWindow borrowBook;
    private ReturnBookWindow returnBook;
    private ViewBooksWindow viewBooks;
    private ViewBorrowedBooksWindow viewBorrowedBooks;
    private LibrarianRole librarianRole;
    /**
     * Creates new form LibrarianRoleWindow
     * @throws java.io.FileNotFoundException
     */
    public LibrarianRoleWindow() throws FileNotFoundException {
        initComponents();
        this.setTitle("Librarian Role");
        addBook = null;
        borrowBook = null;
        returnBook = null;
        viewBooks = null;
        viewBorrowedBooks = null;
        librarianRole = new LibrarianRole();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBookButton = new javax.swing.JButton();
        viewBooksButton = new javax.swing.JButton();
        borrowBookButton = new javax.swing.JButton();
        viewBorrowdBooksButton = new javax.swing.JButton();
        returnBookButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        addBookButton.setBackground(new java.awt.Color(0, 0, 0));
        addBookButton.setForeground(new java.awt.Color(255, 255, 255));
        addBookButton.setText("Add Book");
        addBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButtonActionPerformed(evt);
            }
        });

        viewBooksButton.setBackground(new java.awt.Color(0, 0, 0));
        viewBooksButton.setForeground(new java.awt.Color(255, 255, 255));
        viewBooksButton.setText("View Books");
        viewBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBooksButtonActionPerformed(evt);
            }
        });

        borrowBookButton.setBackground(new java.awt.Color(0, 0, 0));
        borrowBookButton.setForeground(new java.awt.Color(255, 255, 255));
        borrowBookButton.setText("Borrow Book");
        borrowBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowBookButtonActionPerformed(evt);
            }
        });

        viewBorrowdBooksButton.setBackground(new java.awt.Color(0, 0, 0));
        viewBorrowdBooksButton.setForeground(new java.awt.Color(255, 255, 255));
        viewBorrowdBooksButton.setText("View Borrowd Books");
        viewBorrowdBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBorrowdBooksButtonActionPerformed(evt);
            }
        });

        returnBookButton.setBackground(new java.awt.Color(0, 0, 0));
        returnBookButton.setForeground(new java.awt.Color(255, 255, 255));
        returnBookButton.setText("Return Book");
        returnBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookButtonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(0, 0, 0));
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewBorrowdBooksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrowBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewBooksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(addBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewBooksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(borrowBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewBorrowdBooksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(returnBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if(addBook == null){
            try {
                addBook = new AddBookWindow(librarianRole);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(LibrarianRoleWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            addBook.setParentNode(this);
            addBook.setVisible(true);
        }
    }//GEN-LAST:event_addBookButtonActionPerformed

    private void viewBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBooksButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if(viewBooks == null){
            viewBooks = new ViewBooksWindow(new String[] {"Book Id","Title","Author Name","Publisher","No of Copies"});
            viewBooks.setParentNode(this);
        }
        Book [] b = librarianRole.getListOfBooks();
        String [][] tableData = new String[b.length][5];
        for(int i=0; i<b.length; i++){
            tableData[i] = b[i].lineRepresentation().split(",");
        }
        viewBooks.setData(tableData);
        viewBooks.setVisible(true);
    }//GEN-LAST:event_viewBooksButtonActionPerformed

    private void borrowBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowBookButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if(borrowBook == null){
            try {
                borrowBook = new BorrowBookWindow(librarianRole);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(LibrarianRoleWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            borrowBook.setParentNode(this);
            borrowBook.setVisible(true);
        }
    }//GEN-LAST:event_borrowBookButtonActionPerformed

    private void viewBorrowdBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBorrowdBooksButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if(viewBorrowedBooks == null){
            viewBorrowedBooks = new ViewBorrowedBooksWindow(new String[] {"Student Id","Book Id","Borrow Date"});
            viewBorrowedBooks.setParentNode(this);
        }
        StudentBook [] sb = librarianRole.getListOfBorrowingOperations();
        String [][] tableData = new String[sb.length][3];
        for(int i=0; i<sb.length; i++){
            tableData[i] = sb[i].lineRepresentation().split(",");
        }
        viewBorrowedBooks.setData(tableData);
        viewBorrowedBooks.setVisible(true);
    }//GEN-LAST:event_viewBorrowdBooksButtonActionPerformed

    private void returnBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if(returnBook == null){
            try {
                returnBook = new ReturnBookWindow(librarianRole);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(LibrarianRoleWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            returnBook.setParentNode(this);
            returnBook.setVisible(true);
        }
    }//GEN-LAST:event_returnBookButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        try {
            librarianRole.logout();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminRoleWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     * @return 
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LibrarianRoleWindow().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(LibrarianRoleWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }*/

    @Override
    public Node getParentNode() {
        return parent;
    }

    @Override
    public void setParentNode(Node node) {
        this.parent = node;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookButton;
    private javax.swing.JButton borrowBookButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton returnBookButton;
    private javax.swing.JButton viewBooksButton;
    private javax.swing.JButton viewBorrowdBooksButton;
    // End of variables declaration//GEN-END:variables
}
